### ISSUE TITLE
getting oldest messages

### ISSUE THREAD

**Issue by maxogden** [SpiderStrategies/node-gmail-api#10]
heya, this is more a question about the gmail API than anything else

I was experimenting with this to try and write a gmail changes feed module, that would start from the very first message in someones gmail history and go forward chronologically until it reached the latest message.

However, I don't think gmail supports this :( But I hope I am wrong!

The so called [full sync](https://developers.google.com/gmail/api/guides/sync) is actually just a sync of the last weeks worth of messages. The `historyId` that they use to keep 'sync state' expires after a week, and I can't figure out a way to get the historyId of the oldest message in All Mail.

I thought maybe I could use the `q` parameter to do a search query to get old messages so I tried `/messages?q=after:2004/04/01&maxResults=1'` but that gave me the latest message, not the oldest (as I had hoped). I also tried `/history?startHistoryId=0'` but that gave me a Bad Request.

I one option is to download the gmail mbox archive from Google Takeout, but that sucks because there doesn't seem to be a way to sync from where that left off in the case where you haven't synced in over a week.

Another option is to sync latest -> oldest, but theres no way to know what percentage of the way done the sync is that way.

**Edit** Forgot to mention another option which is to use the IMAP API

**Comment by nathanbowser** [comment]
Hi Max.

I'm not sure. I briefly looked into the http api and I don't see how you can reverse the order of messages, so you can grab the oldest. I guess IMAP or sync might be your only option.

Sorry I couldn't help. Hopefully this picture of my friend's cat makes up for it.

![cat](https://cloud.githubusercontent.com/assets/203161/8394005/bf50069c-1cf4-11e5-9455-c1dc708693df.png)

**Comment by maxogden** [comment]
yep, it did!
