### ISSUE TITLE
Definition of <KEY>

### ISSUE THREAD

**Issue by tadwhitaker** [SpiderStrategies/node-gmail-api#16]
Keeping an error saying 'Invalid Credentials' and I think it's because I'm not using the correct Key needed. I've created an API Key (starts with AIzaSyAP...) and OAuth2 Client IDs. I've tried passing in both as strings and getting this error.

Any help would be greatly appreciated.

**Comment by nathanbowser** [comment]
This isn't a bug. Look through older issues where other users have also asked about authentication.
