### ISSUE TITLE
Refresh Tokens

### ISSUE THREAD

**Issue by go4cas** [SpiderStrategies/node-gmail-api#19]
I am still getting the **Invalid Credentials** message. I have now traced this to the following scenario:

- When I create a new `access_token`, the call to get the emails from the selected inbox works 100%
- The issue is that the `access_token` expires after 1 hour
- So, when I have this code: `var gmail = new Gmail(auth.credentials.access_token);` it works before expiry. But, after expiry this `access_code` is obviously no longer valid.

Is there a way to pass in the entire auth object? Or, how would the GMail API get access to the `refresh_token`? Does the `node-gmail-api` package support use of refresh tokens?

**Comment by nathanbowser** [comment]
This is out of the scope of this project. You need to read about oauth refresh tokens, and refresh your token with google. https://developers.google.com/identity/protocols/OAuth2
