### ISSUE TITLE
What should be entered as 'key'

### ISSUE THREAD

**Issue by gtarsia** [SpiderStrategies/node-gmail-api#2]
The example says:

```
// Fetch latest 10 emails and show the snippet
var gmail = new Gmail(key)
```

But someone not familiar with Gmail API doesn't know what to pass as `key`. Can you add that to the documentation?

Thanks.

**Comment by jadeforrest** [comment]
Another suggestion here might be to put "key" in all caps, to make it clear that it is something you want to substitute.
