### ISSUE TITLE
Setup guide request- again "Invalid Credentials"

### ISSUE THREAD

**Issue by yarnball** [SpiderStrategies/node-gmail-api#20]
Hi,

Looks like a great project.

I've looked through the past issues for a few hours but still haven't had success. Keep getting the "Invalid Credentials" error.

Could you be more explicit in the guide?

1. Run `npm install node-gmail-api`

2. Gone to the Gmail console to get an Oatuth 2.0 key 
![2016-08-12 at 9 16 16 pm](https://cloud.githubusercontent.com/assets/13043067/17620895/f9f903ca-60d2-11e6-8f92-4010f5d89f43.jpg)

3. Pasted this key in the following

```
var Gmail = require('node-gmail-api')
  , gmail = new Gmail('71265.....')
  , s = gmail.messages('label:inbox', {max: 10})
 
s.on('data', function (d) {
  console.log(d.snippet)
})
```

You mention using node-passport to get an access key for a user- so am I supposed to use that to generate the key I use above?

**Comment by nathanbowser** [comment]
Yea, client ID isn't your key. You need to authenticate to get a key for a user. I suggest using node-passport to do that.

**Comment by yarnball** [comment]
Thanks. Node-passport has a disclaimer saying "** NOTICE: Google no-longer supports OpenID 2, and this plugin is no longer functional. Please use Passport-Google-OAuth instead. **"

Will https://github.com/jaredhanson/passport-google-oauth get the right 

And am I using this library to get access to a key which I'll paste into the <key> area? Or do I need to do more with that other library?

Thanks

**Comment by nathanbowser** [comment]
https://github.com/jaredhanson/passport-google-oauth should work. Use it to get the key, and put the key into this library.

**Comment by yarnball** [comment]
Sorry that repo doesn't work- most of the files have little code. Do you have another source to get the auth key? Does not have to be node-js
