### ISSUE TITLE
Is this module for read-only operations?

### ISSUE THREAD

**Issue by ferreiro** [SpiderStrategies/node-gmail-api#21]
Hello, I'm looking for a node module for fetching, sending and deleting GMAIL inbox. 
Is this module able to do that? The examples on Readme only fetch the inbox. 

If the answer is yes, do you guys have a webpage for documentation?
If nop, which module do you recommend me?

Thank you.
Jorge.

**Comment by nathanbowser** [comment]
Hey there, Jorge -

This is only for fetching email. We'd take a PR for more functionality, though.

I'm not sure if there's anything already written that writes to the API. I'd bet there is if you look hard enough.

Good luck.

**Comment by ferreiro** [comment]
@nathanbowser Thanks for your response Nathan! Yeah! There are some node modules that writes to gmail API. For example [this](https://www.npmjs.com/package/gmail-send). 

But it would be awesome to have all the  writing and reading functionalities in the same module. So keep working on it! :)
