### ISSUE TITLE
authentication

### ISSUE THREAD

**Issue by webchaz** [SpiderStrategies/node-gmail-api#6]
Do you have any examples of authentication or obtaining the key,  The google-passport module seems to use OpenID and not oAuth2, also not really sure how to do this without having redirect urls? If possible...

Thanks!

**Comment by nathanbowser** [comment]
Hi there. I use the passport google oauth module (https://github.com/jaredhanson/passport-google-oauth)

The code looks like: 

```javascript
 passport.use('google-apps', new GoogleStrategy({
    clientID: conf.config.googleApps.clientId,
    clientSecret: conf.config.googleApps.clientSecret,
    callbackURL: conf.config.baseurl + '/api/account/integration/google-apps/connect/callback'
  }, function (accessToken, tokenSecret, params, profile, done) {
    var now = new Date
  // do your thing
  })
```

This module doesn't do anything with obtaining the key.

Good luck!
